name: swiftlint

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint
      run: |
        ./install_swiftlint.sh
        swiftlint
